# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hayden Schiff
author: Hayden Schiff
email: hayden@schiff.io
description: >
  Software developer. Soccer and anime meganerd. Cincinnati native. He/him.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.schiff.io" # the base hostname & protocol for your site, e.g. http://example.com

# social usernames
bitbucket_username:   oxguy3
facebook_username:    haydenschiff
flickr_username:      oxguy3
github_username:      oxguy3
hackernews_username:  oxguy3
keybase_username:     oxguy3
linkedin_username:    haydenschiff
myanimelist_username: oxguy3
reddit_username:      oxguy3
snapchat_username:    oxguy3
stackoverflow_userid: 992504
steam_username:       oxguy3
twitch_username:      itsoxguy3
twitter_username:     haydenschiff
wikipedia_username:   IagoQnsi

# disqus:
#     shortname: hayden-schiff

# seo
google_analytics: UA-53424623-1
twitter:
    username: haydenschiff
logo: /assets/face500.jpg
google_site_verification: em_CCqIepc-mKuqUKymAjcPxp_48PsmDTLc1hbORMaw
lang: en_US

# build settings
markdown: kramdown
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
highlighter: pygments
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
permalink: /:categories/:year/:month/:day/:title


# tagging
tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag
#ignored_tags: [tags,to,ignore]

# navigation bar
header_pages:
  - about.md
  - projects/index.md
  - blog.md

# default page layout
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: "blog"
      author: "Hayden Schiff"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Hayden Schiff"
